apiVersion: sro.openshift.io/v1beta1
kind: SpecialResourceModule
metadata:
  name: acm-ice
spec:
  namespace: acm-ice
  chart:
    name: acm-ice
    version: 0.0.1
    repository:
      name: chart
      url: file:///charts/example
  set:
    kind: Values
    apiVersion: sro.openshift.io/v1beta1
    buildArgs:
      - name: DRIVER_VER
        value: "1.6.4"
  watch:
    - path: "$.status.history[*].image"
      apiVersion: config.openshift.io/v1
      kind: ClusterVersion
      name: version
